[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
santa_vs_grinch = "5Kox1zWxgz9oGXCYw65iGKAHYmiFov6FpPCib71NZ75x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/programs/metaplex_token_metadata_program.so"
